### ISSUE TITLE
read.adp.rdi() "array" error due to negative `numberOfCells`

### ISSUE THREAD

**Issue by JeroenDeBisschop** [dankelley/oce#594]
I am using the oce package for ADCP (ENS) files, but I keep getting this error when I try to read the files:

```
read.oce("UW2015-02000_000000.ENS")
Error in array(dim = c(profilesToRead, numberOfCells, numberOfBeams)) :
  negative length vectors are not allowed
In addition: Warning messages:
1: In scan(file, what = "char", sep = "\n", n = 1, quiet = TRUE) :
  embedded nul(s) found in input
2: In scan(file, what = "char", sep = "\n", skip = 1, n = 1, quiet = TRUE,  :
  embedded nul(s) found in input
3: In decodeHeaderRDI(buf, debug = debug - 1) :
  unexpected length 53 of fixed-leader-data header; expecting 50 for 'surveyor' or 59 for 'workhorse'.
```
Can this be a problem due to an outdated version of the package or compatibility issues with the ENS files? Thanks in advance!

**Comment by richardsc** [comment]
Hi Jeroen,

Can you provide the output from doing `traceback()` after you get the above error?

Any chance you could (privately) share the data file? Perhaps email a Dropbox link to `clark.richards@gmail.com` and `dan.kelley@dal.ca`?

Also, some details on the setup would be handy -- what type of ADCP, software, etc? ENS usually means VMDAS, so unless it's a new data format I would expect it to work.

Thanks,
Clark

**Comment by richardsc** [comment]
Also, the output from the `sessionInfo()` command would be helpful to see what versions of things you're running.

**Comment by richardsc** [comment]
Hi Jeroen,

I see that you've already emailed the files to Dan. The output from `traceback()` and `sessionInfo()` would still be helpful though.

Clark

**Comment by richardsc** [comment]
The problem seems to be at [line 92 in `adp.rdi.R`](https://github.com/dankelley/oce/blob/develop/R/adp.rdi.R#L92), where the value being returned for `numberOfCells` is mysteriously -128. Clearly a negative number of cells is impossible, so the code chokes.

If I manually change the value of `numberOfCells` to **128** (by dropping into the source code with a `browser()` statement), everything else works fine.

I think Dan should have a look at why that number is coming back negative. See the test code in [oce-issues 594](https://github.com/dankelley/oce-issues/tree/master/594).

**Comment by dankelley** [comment]
I think I've fixed this in ``develop`` but am hoping Clark can have a look before asking Jeroen for a test with the original data.

**Comment by richardsc** [comment]
I can confirm that this seems to be fixed on the `develop` branch. Thanks so much for pointing out this error @JeroenDeBisschop!

Now, to take advantage of the fix you're going to need to build the package from source. Do you know how to do this? I would suggest following the instructions [here](http://dankelley.github.io/oce/installation.html), where number 3 is typically the easiest:

```r
3. Download and build using install_github()
library(devtools)
install_github("dankelley/oce", ref="develop")
install_github("dankelley/ocedata", ref="master")
```

To install from source there are some OS specific requirements that you may need to install (compilers, etc).

**Comment by richardsc** [comment]
Hi @JeroenDeBisschop . Have you been able to test the fix? If it seems like it's resolved your problem, please close the issue (we prefer to have the issue reporter close the issue when they are sure that their problem has been addressed).

**Comment by JeroenDeBisschop** [comment]
After building the package from source as you instructed, part of the problem seems to be resolved but I still get this error:

data<-read.adp.rdi("UW2015-02000_000000.ENS")
Error in array(dim = c(profilesToRead, numberOfCells, numberOfBeams)) :
  negative length vectors are not allowed
In addition: Warning message:
In decodeHeaderRDI(buf, debug = debug - 1) :
  unexpected length 53 of fixed-leader-data header; expecting 50 for 'surveyor' or 59 for 'workhorse'.

**Comment by richardsc** [comment]
The original issue seems to have been addressed in the develop version, based on email communication, so this issue will be closed. It can always be re-opened if necessary.
